version: 2
# goreleaser release --snapshot --clean
project_name: edgeCore
dist: ./dist

before:
  hooks:
    - go mod tidy
    - npm run build --prefix ./ui # npm run dev --prefix ./ui

builds:
  - id: edgeCore
    main: ./cmd/main.go
    binary: edgeCore
    flags:
      - -trimpath
      - -mod=mod
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X github.com/anviod/edgeCore/internal/model.Version={{.Version}}
      -X github.com/anviod/edgeCore/internal/model.BuildTime={{.Date}}
      -X github.com/anviod/edgeCore/internal/model.CommitID={{.ShortCommit}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - id: edgeCore-archive
    formats:
      - tar.gz
    name_template: '{{.ProjectName}}-{{.RawVersion}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    files:
      - README*
      - LICENSE*
      - conf/**
      - scripts/**
      - edgeCore.service
      - edgeCore.sh
      - ui/dist/**

nfpms:
  - id: edgeCore-deb
    package_name: edgeCore
    file_name_template: 'edgeCore-v{{.RawVersion}}-{{.Arch}}'
    formats:
      - deb
      - rpm
    vendor: HNE Inc.
    homepage: https://github.com/anviod/edgeCore
    maintainer: anviod <anviod@aliyun.com>
    description: 边缘网关，基于 Go 语言的边缘网络通讯与同步服务
    license: GPL-3.0
    bindir: /usr/local/bin/edgeCore
    contents:
      - src: ./edgeCore.service
        dst: /etc/systemd/system/edgeCore.service
        type: config
      - src: ./edgeCore.sh
        dst: /usr/local/bin/edgeCore/edgeCore.sh
      - src: ./conf
        dst: /usr/local/bin/edgeCore/conf
        type: tree
      - src: ./ui/dist
        dst: /usr/local/bin/edgeCore/ui/dist
        type: tree
    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh

checksum:
  name_template: SHA256SUMS
  algorithm: sha256

release:
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
